server:
  port: 8080
spring:
  application:
    name: spring-data-jpa
  datasource:
    read:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driverClassName: org.h2.Driver
#    read:
#      url: jdbc:postgresql://localhost:5432/sample
#      username: postgres
#      password: admin
#      driverClassName: org.postgresql.Driver
    write:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: admin
      driverClassName: org.postgresql.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false